export default {
  "hebrew-aramic": [
    {
      name: "Genesis",
      abbreviation: "Ge",
      chapters: 50,
      verses: 1533,
    },
    {
      name: "Exodus",
      abbreviation: "Ex",
      chapters: 40,
      verses: 1213,
    },
    {
      name: "Leviticus",
      abbreviation: "Le",
      chapters: 27,
      verses: 859,
    },
    {
      name: "Numbers",
      abbreviation: "Nu",
      chapters: 36,
      verses: 1288,
    },
    {
      name: "Deuteronomy",
      abbreviation: "De",
      chapters: 34,
      verses: 959,
    },
    {
      name: "Joshua",
      abbreviation: "Jos",
      chapters: 24,
      verses: 658,
    },
    {
      name: "Judges",
      abbreviation: "Jg",
      chapters: 21,
      verses: 618,
    },
    {
      name: "Ruth",
      abbreviation: "Ru",
      chapters: 4,
      verses: 85,
    },
    {
      name: "1 Samuel",
      abbreviation: "1Sa",
      chapters: 31,
      verses: 810,
    },
    {
      name: "2 Samuel",
      abbreviation: "2Sa",
      chapters: 24,
      verses: 695,
    },
    {
      name: "1 Kings",
      abbreviation: "1Ki",
      chapters: 22,
      verses: 816,
    },
    {
      name: "2 Kings",
      abbreviation: "2Ki",
      chapters: 25,
      verses: 719,
    },
    {
      name: "1 Chronicles",
      abbreviation: "1Ch",
      chapters: 29,
      verses: 942,
    },
    {
      name: "2 Chronicles",
      abbreviation: "2Ch",
      chapters: 36,
      verses: 822,
    },
    {
      name: "Ezra",
      abbreviation: "Ezr",
      chapters: 10,
      verses: 280,
    },
    {
      name: "Nehemiah",
      abbreviation: "Ne",
      chapters: 13,
      verses: 406,
    },
    {
      name: "Esther",
      abbreviation: "Es",
      chapters: 10,
      verses: 167,
    },
    {
      name: "Job",
      abbreviation: "Job",
      chapters: 42,
      verses: 1070,
    },
    {
      name: "Psalms",
      abbreviation: "Ps",
      chapters: 150,
      verses: 2461,
    },
    {
      name: "Proverbs",
      abbreviation: "Pr",
      chapters: 31,
      verses: 915,
    },
    {
      name: "Ecclesiastes",
      abbreviation: "Ec",
      chapters: 12,
      verses: 222,
    },
    {
      name: "Song of Solomon",
      abbreviation: "Ca",
      chapters: 8,
      verses: 117,
    },
    {
      name: "Isaiah",
      abbreviation: "Isa",
      chapters: 66,
      verses: 1292,
    },
    {
      name: "Jeremiah",
      abbreviation: "Jer",
      chapters: 52,
      verses: 1364,
    },
    {
      name: "Lamentations",
      abbreviation: "La",
      chapters: 5,
      verses: 154,
    },
    {
      name: "Ezekiel",
      abbreviation: "Eze",
      chapters: 48,
      verses: 1273,
    },
    {
      name: "Daniel",
      abbreviation: "Da",
      chapters: 12,
      verses: 357,
    },
    {
      name: "Hosea",
      abbreviation: "Ho",
      chapters: 14,
      verses: 197,
    },
    {
      name: "Joel",
      abbreviation: "Joe",
      chapters: 3,
      verses: 73,
    },
    {
      name: "Amos",
      abbreviation: "Am",
      chapters: 9,
      verses: 146,
    },
    {
      name: "Obadiah",
      abbreviation: "Ob",
      chapters: 1,
      verses: 21,
    },
    {
      name: "Jonah",
      abbreviation: "Jon",
      chapters: 4,
      verses: 48,
    },
    {
      name: "Micah",
      abbreviation: "Mic",
      chapters: 7,
      verses: 105,
    },
    {
      name: "Nahum",
      abbreviation: "Na",
      chapters: 3,
      verses: 47,
    },
    {
      name: "Habakkuk",
      abbreviation: "Hab",
      chapters: 3,
      verses: 56,
    },
    {
      name: "Zephaniah",
      abbreviation: "Zep",
      chapters: 3,
      verses: 53,
    },
    {
      name: "Haggai",
      abbreviation: "Hag",
      chapters: 2,
      verses: 38,
    },
    {
      name: "Zechariah",
      abbreviation: "Zec",
      chapters: 14,
      verses: 211,
    },
    {
      name: "Malachi",
      abbreviation: "Mal",
      chapters: 4,
      verses: 55,
    }
  ],
  "christian greek": [
    {
      name: "Matthew",
      abbreviation: "Mt",
      chapters: 28,
      verses: 1071,
    },
    {
      name: "Mark",
      abbreviation: "Mr",
      chapters: 16,
      verses: 678,
    },
    {
      name: "Luke",
      abbreviation: "Lu",
      chapters: 24,
      verses: 1151,
    },
    {
      name: "John",
      abbreviation: "Joh",
      chapters: 21,
      verses: 879,
    },
    {
      name: "Acts",
      abbreviation: "Ac",
      chapters: 28,
      verses: 1007,
    },
    {
      name: "Romans",
      abbreviation: "Ro",
      chapters: 16,
      verses: 433,
    },
    {
      name: "1 Corinthians",
      abbreviation: "1Co",
      chapters: 16,
      verses: 437,
    },
    {
      name: "2 Corinthians",
      abbreviation: "2Co",
      chapters: 13,
      verses: 257,
    },
    {
      name: "Galatians",
      abbreviation: "Ga",
      chapters: 6,
      verses: 149,
    },
    {
      name: "Ephesians",
      abbreviation: "Eph",
      chapters: 6,
      verses: 155,
    },
    {
      name: "Philippians",
      abbreviation: "Php",
      chapters: 4,
      verses: 104,
    },
    {
      name: "Colossians",
      abbreviation: "Col",
      chapters: 4,
      verses: 95,
    },
    {
      name: "1 Thessalonians",
      abbreviation: "1Th",
      chapters: 5,
      verses: 89,
    },
    {
      name: "2 Thessalonians",
      abbreviation: "2Th",
      chapters: 3,
      verses: 47,
    },
    {
      name: "1 Timothy",
      abbreviation: "1Ti",
      chapters: 6,
      verses: 113,
    },
    {
      name: "2 Timothy",
      abbreviation: "2Ti",
      chapters: 4,
      verses: 83,
    },
    {
      name: "Titus",
      abbreviation: "Tit",
      chapters: 3,
      verses: 46,
    },
    {
      name: "Philemon",
      abbreviation: "Phm",
      chapters: 1,
      verses: 25,
    },
    {
      name: "Hebrews",
      abbreviation: "Heb",
      chapters: 13,
      verses: 303,
    },
    {
      name: "James",
      abbreviation: "Jas",
      chapters: 5,
      verses: 108,
    },
    {
      name: "1 Peter",
      abbreviation: "1Pe",
      chapters: 5,
      verses: 105,
    },
    {
      name: "2 Peter",
      abbreviation: "2Pe",
      chapters: 3,
      verses: 61,
    },
    {
      name: "1 John",
      abbreviation: "1Jo",
      chapters: 5,
      verses: 105,
    },
    {
      name: "2 John",
      abbreviation: "2Jo",
      chapters: 1,
      verses: 13,
    },
    {
      name: "3 John",
      abbreviation: "3Jo",
      chapters: 1,
      verses: 15,
    },
    {
      name: "Jude",
      abbreviation: "Jude",
      chapters: 1,
      verses: 25,
    },
    {
      name: "Revelation",
      abbreviation: "Re",
      chapters: 22,
      verses: 404,
    }
  ],
}

export const plainStructure = [
  {
    name: "Genesis",
    abbreviation: "Ge",
    chapters: 50,
    // verses: 1533,
  },
  {
    name: "Exodus",
    abbreviation: "Ex",
    chapters: 40,
    // verses: 1213,
  },
  {
    name: "Leviticus",
    abbreviation: "Le",
    chapters: 27,
    // verses: 859,
  },
  {
    name: "Numbers",
    abbreviation: "Nu",
    chapters: 36,
    // verses: 1288,
  },
  {
    name: "Deuteronomy",
    abbreviation: "De",
    chapters: 34,
    // verses: 959,
  },
  {
    name: "Joshua",
    abbreviation: "Jos",
    chapters: 24,
    // verses: 658,
  },
  {
    name: "Judges",
    abbreviation: "Jg",
    chapters: 21,
    // verses: 618,
  },
  {
    name: "Ruth",
    abbreviation: "Ru",
    chapters: 4,
    // verses: 85,
  },
  {
    name: "1 Samuel",
    abbreviation: "1Sa",
    chapters: 31,
    // verses: 810,
  },
  {
    name: "2 Samuel",
    abbreviation: "2Sa",
    chapters: 24,
    // verses: 695,
  },
  {
    name: "1 Kings",
    abbreviation: "1Ki",
    chapters: 22,
    // verses: 816,
  },
  {
    name: "2 Kings",
    abbreviation: "2Ki",
    chapters: 25,
    // verses: 719,
  },
  {
    name: "1 Chronicles",
    abbreviation: "1Ch",
    chapters: 29,
    // verses: 942,
  },
  {
    name: "2 Chronicles",
    abbreviation: "2Ch",
    chapters: 36,
    // verses: 822,
  },
  {
    name: "Ezra",
    abbreviation: "Ezr",
    chapters: 10,
    // verses: 280,
  },
  {
    name: "Nehemiah",
    abbreviation: "Ne",
    chapters: 13,
    // verses: 406,
  },
  {
    name: "Esther",
    abbreviation: "Es",
    chapters: 10,
    // verses: 167,
  },
  {
    name: "Job",
    abbreviation: "Job",
    chapters: 42,
    // verses: 1070,
  },
  {
    name: "Psalms",
    abbreviation: "Ps",
    chapters: 150,
    // verses: 2461,
  },
  {
    name: "Proverbs",
    abbreviation: "Pr",
    chapters: 31,
    // verses: 915,
  },
  {
    name: "Ecclesiastes",
    abbreviation: "Ec",
    chapters: 12,
    // verses: 222,
  },
  {
    name: "Song of Solomon",
    abbreviation: "Ca",
    chapters: 8,
    // verses: 117,
  },
  {
    name: "Isaiah",
    abbreviation: "Isa",
    chapters: 66,
    // verses: 1292,
  },
  {
    name: "Jeremiah",
    abbreviation: "Jer",
    chapters: 52,
    // verses: 1364,
  },
  {
    name: "Lamentations",
    abbreviation: "La",
    chapters: 5,
    // verses: 154,
  },
  {
    name: "Ezekiel",
    abbreviation: "Eze",
    chapters: 48,
    // verses: 1273,
  },
  {
    name: "Daniel",
    abbreviation: "Da",
    chapters: 12,
    // verses: 357,
  },
  {
    name: "Hosea",
    abbreviation: "Ho",
    chapters: 14,
    // verses: 197,
  },
  {
    name: "Joel",
    abbreviation: "Joe",
    chapters: 3,
    // verses: 73,
  },
  {
    name: "Amos",
    abbreviation: "Am",
    chapters: 9,
    // verses: 146,
  },
  {
    name: "Obadiah",
    abbreviation: "Ob",
    chapters: 1,
    // verses: 21,
  },
  {
    name: "Jonah",
    abbreviation: "Jon",
    chapters: 4,
    // verses: 48,
  },
  {
    name: "Micah",
    abbreviation: "Mic",
    chapters: 7,
    // verses: 105,
  },
  {
    name: "Nahum",
    abbreviation: "Na",
    chapters: 3,
    // verses: 47,
  },
  {
    name: "Habakkuk",
    abbreviation: "Hab",
    chapters: 3,
    // verses: 56,
  },
  {
    name: "Zephaniah",
    abbreviation: "Zep",
    chapters: 3,
    // verses: 53,
  },
  {
    name: "Haggai",
    abbreviation: "Hag",
    chapters: 2,
    // verses: 38,
  },
  {
    name: "Zechariah",
    abbreviation: "Zec",
    chapters: 14,
    // verses: 211,
  },
  {
    name: "Malachi",
    abbreviation: "Mal",
    chapters: 4,
    // verses: 55,
  },
  {
    name: "Matthew",
    abbreviation: "Mt",
    chapters: 28,
    // verses: 1071,
  },
  {
    name: "Mark",
    abbreviation: "Mr",
    chapters: 16,
    // verses: 678,
  },
  {
    name: "Luke",
    abbreviation: "Lu",
    chapters: 24,
    // verses: 1151,
  },
  {
    name: "John",
    abbreviation: "Joh",
    chapters: 21,
    // verses: 879,
  },
  {
    name: "Acts",
    abbreviation: "Ac",
    chapters: 28,
    // verses: 1007,
  },
  {
    name: "Romans",
    abbreviation: "Ro",
    chapters: 16,
    // verses: 433,
  },
  {
    name: "1 Corinthians",
    abbreviation: "1Co",
    chapters: 16,
    // verses: 437,
  },
  {
    name: "2 Corinthians",
    abbreviation: "2Co",
    chapters: 13,
    // verses: 257,
  },
  {
    name: "Galatians",
    abbreviation: "Ga",
    chapters: 6,
    // verses: 149,
  },
  {
    name: "Ephesians",
    abbreviation: "Eph",
    chapters: 6,
    // verses: 155,
  },
  {
    name: "Philippians",
    abbreviation: "Php",
    chapters: 4,
    // verses: 104,
  },
  {
    name: "Colossians",
    abbreviation: "Col",
    chapters: 4,
    // verses: 95,
  },
  {
    name: "1 Thessalonians",
    abbreviation: "1Th",
    chapters: 5,
    // verses: 89,
  },
  {
    name: "2 Thessalonians",
    abbreviation: "2Th",
    chapters: 3,
    // verses: 47,
  },
  {
    name: "1 Timothy",
    abbreviation: "1Ti",
    chapters: 6,
    // verses: 113,
  },
  {
    name: "2 Timothy",
    abbreviation: "2Ti",
    chapters: 4,
    // verses: 83,
  },
  {
    name: "Titus",
    abbreviation: "Tit",
    chapters: 3,
    // verses: 46,
  },
  {
    name: "Philemon",
    abbreviation: "Phm",
    chapters: 1,
    // verses: 25,
  },
  {
    name: "Hebrews",
    abbreviation: "Heb",
    chapters: 13,
    // verses: 303,
  },
  {
    name: "James",
    abbreviation: "Jas",
    chapters: 5,
    // verses: 108,
  },
  {
    name: "1 Peter",
    abbreviation: "1Pe",
    chapters: 5,
    // verses: 105,
  },
  {
    name: "2 Peter",
    abbreviation: "2Pe",
    chapters: 3,
    // verses: 61,
  },
  {
    name: "1 John",
    abbreviation: "1Jo",
    chapters: 5,
    // verses: 105,
  },
  {
    name: "2 John",
    abbreviation: "2Jo",
    chapters: 1,
    // verses: 13,
  },
  {
    name: "3 John",
    abbreviation: "3Jo",
    chapters: 1,
    // verses: 15,
  },
  {
    name: "Jude",
    abbreviation: "Jude",
    chapters: 1,
    // verses: 25,
  },
  {
    name: "Revelation",
    abbreviation: "Re",
    chapters: 22,
    // verses: 404,
  }
]
export const absoluteChapterNumber = {
  'Бытие': 50,
  'Исход': 90,
  'Левит': 117,
  'Числа': 153,
  'Второзаконие': 187,
  'Иисус Навин': 211,
  'Книга Судей': 232,
  'Руфь': 236,
  '1-я Царств': 267,
  '2-я Царств': 291,
  '3-я Царств': 313,
  '4-я Царств': 338,
  '1-я Паралипоменон': 367,
  '2-я Паралипоменон': 403,
  'Ездра': 413,
  'Неемия': 426,
  'Есфирь': 436,
  'Иов': 478,
  'Псалтирь': 628,
  'Притчи': 659,
  'Екклесиаст': 671,
  'Песни Песней': 679,
  'Исаия': 745,
  'Иеремия': 797,
  'Плач Иеремии': 802,
  'Иезекииль': 850,
  'Даниил': 862,
  'Осия': 876,
  'Иоиль': 879,
  'Амос': 888,
  'Авдия': 889,
  'Иона': 893,
  'Михей': 900,
  'Наум': 903,
  'Аввакум': 906,
  'Софония': 909,
  'Аггей': 911,
  'Захария': 925,
  'Малахия': 929,
  'От Матфея': 957,
  'От Марка': 973,
  'От Луки': 997,
  'От Иоанна': 1018,
  'Деяния': 1046,
  'К Римлянам': 1062,
  '1-е Коринфянам': 1078,
  '2-е Коринфянам': 1091,
  'К Галатам': 1097,
  'К Ефесянам': 1103,
  'К Филиппийцам': 1107,
  'К Колоссянам': 1111,
  '1-е Фессалоникийцам': 1116,
  '2-е Фессалоникийцам': 1119,
  '1-е Тимофею': 1125,
  '2-е Тимофею': 1129,
  'К Титу': 1132,
  'К Филимону': 1133,
  'К Евреям': 1146,
  'Иакова': 1151,
  '1-e Петра': 1156,
  '2-e Петра': 1159,
  '1-e Иоанна': 1164,
  '2-e Иоанна': 1165,
  '3-e Иоанна': 1166,
  'Иуда': 1167,
  'Откровение': 1189
}
export const maxChapters = 1189
